from transformers import pipeline

# I loaded the summarization pipeline

summarizer= pipeline('summarization')

# get the data we want to summairze 
data="""
Robotic surgery is a modern advancement in healthcare that allows doctors to perform complex procedures with greater precision, flexibility, and control. Using a robotic system with a camera and mechanical arms, surgeons can operate through small incisions, leading to less pain, faster recovery, and reduced complications. While this technology offers many benefits, there are still concerns about legal responsibilities and regulations. As robotic surgery continues to evolve, it has the potential to improve patient outcomes and make specialized care more accessible.
Robotic surgery helps doctors perform complex procedures with more precision, flexibility, and control than traditional methods. It is usually done through small incisions but can also be used in open surgeries. Also called robot-assisted surgery, it involves a robotic system with a camera arm and mechanical arms holding surgical tools. The surgeon controls these arms from a nearby console while viewing a clear, 3D images of the surgical site. The technology has three main components: robotic arms, a high-definition camera, and a surgical console. The robotic arms hold tiny surgical instruments, while the high-definition camera provides a magnified, 3D view of the surgical area. The surgeon works with a console, controlling the instruments and camera with joystick-like controls like those in an arcade game. Robotic surgery does not replace your surgeon; it is just another tool they use. The techniques are like traditional open surgery, but the key difference is access. Instead of one large incision, the surgeon makes a few small ones. The robotic instruments also need less space, reducing the need to move tissue, muscles, and organs aside. Robotic system can be considered as a supercomputer that translates the surgeon’s movements into real-time actions for greater precision. During surgery, the surgeon uses a console with master controls to direct the instruments. The computer ensures the instruments move exactly as the surgeon does inside the body. The surgeon is always in control, and the system responds to their commands.
There are many benefits to having Robotic-assisted surgery. A Robotic-assisted surgery benefits you directly—shorter recovery time—as well as indirectly—the surgeon has better visualization, leading to a more precise surgery. Benefits include, surgeons have a greater range of motion and dexterity. He sees a highly magnified, high-resolution image of the operating field. The surgeon can access the area which is being operated on. Chances of less complications during surgery increases and allows shorter hospital to stay. It also includes less risk of infection and blood loss and fewer blood transfusions. The surgery also can provide virtual information, enhanced precision in spatial resolution and geometric accuracy, improved dexterity, faster maneuverability, and fatigue-free operation, ensuring consistent and steady motion. It also enables less invasive procedures, reducing blood loss and shortening postoperative recovery times, such as hospital stays. These benefits contribute to better patient outcomes. I think the benefits of robotic surgery are greater than the challenges. Technology helps improve precision and reduces recovery time, making surgeries less invasive and minimizing risks like blood loss or infections. Surgeons can operate with greater control and without fatigue, which leads to better outcomes. 
However, there is always an uncertainty that stays regarding a surgeon’s legal responsibility if a robotic system malfunctions. There are ongoing debates about the manufacturer’s liability and whether the necessary quality checks and government approvals have been met. Creating laws and guidelines for robotic surgery is complex, as each country must consider its legal framework and societal factors to develop regulations that align with existing laws. As this technology continues to evolve, surgeons must approach it carefully, staying mindful of potential risks rather than ignoring them.
Robotic surgery is a significant improvement in healthcare, providing more precise surgeries, smaller cuts, and quicker recovery. It can help patients have better outcomes and make specialized care more accessible through remote surgeries. However, there are still challenges around who is responsible if something goes wrong, and regulations are needed to protect patients. The future of robotic surgery looks bright, with even better systems and AI to help doctors make better decisions.

"""
summary= summarizer(data, max_length=200, min_length=30, do_sample=True)

print(summary)